apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "test-shipyard"
spec:
  stages:
    - name: "performancetests"
      tasks:
      - name: "deployment"                  
        properties:
          deploymentstrategy: "direct"
      - name: "test"                  
        properties:
          teststrategy: "performance"
      - name: "evaluation"